name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo tests
        run: cargo test --all --verbose

      - name: Run rust coverage
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --out Xml --timeout 120

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: tarpaulin-report
          path: cobertura.xml
